### basic route
GET http://localhost:8000



### set admin 
POST http://localhost:8000/auth/set



### admin login
POST http://localhost:8000/auth/login
content-type: application/json

{
    "email": "admin@ems.com",
    "password": "admin123"
}



### add new employee
POST http://localhost:8000/api/new
content-type: application/json

{
    "first_name": "adel",
    "last_name": "kholza",
    "email": "adel@ems.com",
    "gender": "male",
    "contactno": "0987654321"
}



### list all employees
GET http://localhost:8000/api/list