### basic route
GET http://localhost:8000



### set admin 
POST http://localhost:8000/auth/set



### admin login
POST http://localhost:8000/auth/login
content-type: application/json

{
    "email": "admin@ems.com",
    "password": "admin123"
}



### add new employee
POST http://localhost:8000/api/new
content-type: application/json

{
    "first_name": "adel",
    "last_name": "kholza",
    "email": "adel@ems.com",
    "gender": "male",
    "contactno": "0987654321"
}



### list all employees
GET http://localhost:8000/api/emps



### add employment details
POST http://localhost:8000/api/employ
content-type: application/json

{
    "employee": 1,
    "position": "technician",
    "start_date": "1/11/2023",
    "salary": 5000
}



### list all employees and their employment details
GET http://localhost:8000/api/list



### one employee and their employment details
GET http://localhost:8000/api/one/2



### edit/update employee and their employment details
PUT http://localhost:8000/api/update/1
content-type: application/json

{
    "position": "technician",
    "emp_status": "active",
    "salary": 3500.00
}


### remove/delete an employee
GET http://localhost:8000/api/remove/15